#
# BTstack example 'hid_host_demo' for ESP32 port
#
# Generated by /Users/brew/esp/btstack-master/port/esp32
# On Sun Jan 12 01:16:56 2020

PROJECT_NAME := retrotooth

include $(IDF_PATH)/make/project.mk
